# Generated by Django 3.0.6 on 2021-02-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=64, unique=True)),
                ('case_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('post_code', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('nip', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LeadingPersonClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.LeadingPerson')),
            ],
        ),
        migrations.AddField(
            model_name='leadingperson',
            name='client',
            field=models.ManyToManyField(through='project.LeadingPersonClient', to='project.Client'),
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('nip', models.CharField(max_length=10, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('corespondent_cost', models.BooleanField()),
                ('law_cost', models.BooleanField()),
                ('zaliczka', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee', models.CharField(max_length=64)),
                ('account_number', models.CharField(max_length=26)),
                ('transfer_title', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('document', models.IntegerField(choices=[(1, 'fatura'), (2, 'nota księgowa')])),
                ('rodzaj_rozliczenia', models.IntegerField(choices=[(1, 'WYDATEK'), (2, 'WPŁYW')], null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client')),
                ('id_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Case')),
                ('id_debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Debtor')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Client'),
        ),
        migrations.AddField(
            model_name='case',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Debtor'),
        ),
    ]
